# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-11 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_ext', '0001_initial'),
        ('base', '0027_auto_20170801_1228_squashed_0037_auto_20190222_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='data_accessibility',
            field=models.CharField(blank=True, default=b'', help_text='a Data Accessibility will be added by Admin before publication.', max_length=200, null=True, verbose_name='data accessibility'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='data_portal',
            field=models.ForeignKey(blank=True, help_text='a Data Portal will be added by Admin before publication.', null=True, on_delete=django.db.models.deletion.CASCADE, to='base_ext.DataPortal'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='domain_area',
            field=models.ManyToManyField(blank=True, help_text='a Domain Area will be added by Admin before publication.', related_name='resourcebase_domainarea', to='base_ext.DomainArea'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='starred',
            field=models.CharField(blank=True, default=b'', help_text='a Starred will be added by Admin before publication.', max_length=200, null=True, verbose_name='starred'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='validation_level',
            field=models.ForeignKey(blank=True, help_text='a Validation Level will be added by Admin before publication.', null=True, on_delete=django.db.models.deletion.CASCADE, to='base_ext.ValidationLevel'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='main_category',
            field=models.ForeignKey(blank=True, help_text='a Main Category will be added by Admin before publication.', null=True, on_delete=django.db.models.deletion.CASCADE, to='base_ext.MainCategory'),
        ),
    ]
