# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-06 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20191104_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='data_accessibility',
            field=models.TextField(blank=True, default=b'', help_text='a Data Accessibility will be added by Admin before publication.', null=True, verbose_name='data accessibility'),
        ),
    ]