# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-23 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_auto_20190516_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='abstract_en',
            field=models.TextField(blank=True, help_text='brief narrative summary of the content of the resource(s)', max_length=5000, null=True, verbose_name='abstract'),
        ),
    ]
